# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Install Microsoft Edge
        run: |
          wget https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_124.0.2478.80-1_amd64.deb
          sudo dpkg -i microsoft-edge-stable_124.0.2478.80-1_amd64.deb || sudo apt-get -f install -y

      - name: Install EdgeDriver
        run: |
          EDGEDRIVER_VERSION=$(curl -sSL https://msedgedriver.azureedge.net/LATEST_STABLE)
          wget https://msedgedriver.azureedge.net/${EDGEDRIVER_VERSION}/edgedriver_linux64.zip
          unzip edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/edgedriver
          sudo chmod +x /usr/local/bin/edgedriver

      - name: Build and Test with Maven
        run: mvn -B verify --file pom.xml
